### ISSUE TITLE
Proposal to add an indoor surveillance project with Tello + (API simulation in Webots)

### ISSUE THREAD

**Issue by juanmill4** [Matthias84/awesome-tello#1]
This project involves using a DJI Tello drone for indoor surveillance, designed for enclosed environments where precision and maneuverability in restricted spaces are essential. It uses Webots for environment simulation, allowing for testing and adjustments before real-world deployment.

https://github.com/juanmill4/Indoor-Autonomous-Tello

+ API Webots Simulation https://github.com/juanmill4/API-Tello-tellopy-Webots

Thanks.

**Comment by Matthias84** [comment]
Pretty new, but I'm ok with that. Will you start a PR?

P.S: Uses your simulation an existing indoor model or will it discover it's environment during operration?

**Comment by juanmill4** [comment]
The model discover environment during operation at mapping state with fiducal markers.

Okay I make a Pull Request, Thanks

**Comment by Matthias84** [comment]
merged, thanks :slightly_smiling_face:
